import type { Metadata } from "next";

//components
import { Footer, Header } from "@/commons/components";
import { ThemeRegistry, StyledComponentsRegistry } from "@/commons/configs";

//Assets
import "@/assets/css/general.css";

export const metadata: Metadata = {
	title: "Rockie",
	description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
	return (
		<html lang="en">
			<body>
				<StyledComponentsRegistry>
					<ThemeRegistry>
						<Header />
						{children}
						<Footer />
					</ThemeRegistry>
				</StyledComponentsRegistry>
			</body>
		</html>
	);
};

export default Layout;
