import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/Assets/css/general.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Rockie",
	description: "Generated by me",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<Head>
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
